[target.wasm32-unknown-unknown]
rustflags = [
  "-C",
  "target-feature=+crt-static",
  "-C",
  "link-arg=--import-memory",
  "-C",
  "link-arg=--initial-memory=65536",
  "-C",
  "link-arg=--max-memory=65536",
  "-C",
  "link-arg=--stack-first",
  "-C",
  "link-arg=--export-table",
]

[env]
CC_wasm32-unknown-unknown = "clang"
AR_wasm32-unknown-unknown = "llvm-ar"
